
---
# This playbook contains common plays that will be run on all nodes.
# asagidaki iki task hostname plugin tarafindan yanlis olusturulan /etc/HOSTS
# girdilerini duzeltmektedir.
- name: init kubeadm
  command: kubeadm init --apiserver-advertise-address={{ansible_eth1.ipv4.address}} --apiserver-cert-extra-sans={{ansible_eth1.ipv4.address}}  --node-name {{ansible_hostname}} --pod-network-cidr=192.168.60.0/24


- name: copy credentials to vagrant remote_user
  shell: scripts/crdcopy.sh >>log.txt
